name: Build Android APK

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4  # Updated to v4

      - name: Get Date
        id: get-date
        run: |
          echo "date=$(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT

      - name: Build with Buildozer
        uses: ArtemSBulgakov/buildozer-action@v1
        with:
          buildozer_version: stable
          python_version: 3.11

      - name: Upload APK
        uses: actions/upload-artifact@v4  # Updated to v4
        with:
          name: MediaDownloader-APK-${{ steps.get-date.outputs.date }}
          path: bin/*.apk
